- name: Testing TKO
  hosts: localhost
  gather_facts: false
  
  tasks:

  - name: Test TKO
    tko: 
    register: result

  - debug: var=result

- name: All hosts
  hosts: all
  gather_facts: false

  tasks:

  - name: Print
    debug: var=testvar
    