---
- name: Testing Custom Module
  hosts: nodes
  gather_facts: false
  collections:
  - ginigangadharan.collection_demo
  tasks:
    - name: Calling customhello2 module
      hello_message:
        message: "Hello"
        name: "John"
      register: custom_value

    - debug:
        msg: "{{ custom_value }}"
