- name: Initialize AWX for TKO
  hosts: localhost
  gather_facts: false

  tasks:

  - name: Create "Deploy site" workflow
    register: result
    awx.awx.workflow_job_template:
      controller_host: http://localhost:30053 # see: assets/kubernetes/kind/tko.yaml
      controller_username: admin
      controller_password: tko  # see: assets/kubernetes/workloads/awx.yaml (awx-admin secret)

      name: Deploy site
      organization: Default
      inventory: TKO

      workflow_nodes:

      - identifier: Infra
        unified_job_template:
          type: job_template
          name: Deploy free5GC UPF
        related:
          success_nodes:
          - identifier: Workload1
          - identifier: Workload2

      - identifier: Workload1
        unified_job_template:
          type: job_template
          name: Deploy free5GC UPF

      - identifier: Workload2
        unified_job_template:
          type: job_template
          name: Deploy free5GC UPF

  - debug: var=result
