- name: Testing Galaxy
  hosts: all
  gather_facts: false
  
  collections:
  - ginigangadharan.collection_demo
  - kubernetes.core
  - ansible.netcommon

  tasks:
  - name: Calling customhello2 module
    hello_message:
      message: "Hello"
      name: "John"
    register: custom_value

  - debug:
      msg: "{{ custom_value }}"
