apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

name: tko
nodes:
- role: control-plane
  extraMounts:
  # hostPaths will be created by root user
  - containerPath: /mnt/postgresql
    hostPath: /tmp/tko/postgresql
  - containerPath: /mnt/docker
    hostPath: /tmp/tko/docker
  - containerPath: /mnt/awx-projects
    hostPath: /tmp/tko/awx-projects
  extraPortMappings:
  # See: workloads/tko-data.yaml
  # tko-data gRPC
  - containerPort: 30050
    hostPort: 30050
  # tko-data HTTP
  - containerPort: 30051
    hostPort: 30051
  # tko-data Kubernetes
  - containerPort: 30052
    hostPort: 30052
  # See: workloads/awx.yaml
  - containerPort: 30053
    hostPort: 30053
networking:
  ipFamily: dual
