apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

name: tko
nodes:
- role: control-plane
  extraMounts:
  - containerPath: /mnt/postgresql
    hostPath: /tmp/tko-postgresql # will be owned by root user
  - containerPath: /mnt/docker
    hostPath: /tmp/tko-docker # will be owned by root user
  extraPortMappings:
  - containerPort: 30050
    hostPort: 30050
  - containerPort: 30051
    hostPort: 30051
  - containerPort: 30052
    hostPort: 30052
