apiVersion: v1
kind: Pod

metadata:
  name: tko-runner
  namespace: tko
  labels:
    app.kubernetes.io/name: tko-runner
    app.kubernetes.io/part-of: tko

spec:
  serviceAccountName: tko
  containers:
  - name: tko-runner
    image: tko-runner
    imagePullPolicy: Always
    env:
    - name: DOCKER_HOST
      value: tcp://127.0.0.1:2375
  - name: docker
    image: docker-dind
    command: [ dockerd, --host, tcp://127.0.0.1:2375 ]
    securityContext:
      privileged: true
    ports:
    - name: docker
      containerPort: 2375
