apiVersion: apps/v1
kind: Deployment

metadata:
  name: tko-api
  namespace: tko
  labels:
    app.kubernetes.io/name: tko-api
    app.kubernetes.io/part-of: tko

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tko-api
      app.kubernetes.io/part-of: tko
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tko-api
        app.kubernetes.io/part-of: tko
    spec:
      serviceAccountName: tko
      containers:
      - name: tko-api
        image: tko-api
        imagePullPolicy: Always
        env:
        - name: TKO_verbose
          value: "1"
        - name: TKO_kubernetes
          value: "true"
        - name: TKO_name
          value: Local Kubernetes
        - name: TKO_description
          value: Kind cluster
        - name: TKO_web-timezone
          value: America/Chicago
        - name: TKO_backend
          value: postgresql
        - name: TKO_backend-clean
          value: "true"
        - name: TKO_backend-connection
          value: postgresql://tko:tko@postgresql:5432/tko
        - name: TKO_backend-connection-timeout
          value: "300.0" # 5 minutes; PostgreSQL can be slow to start up
        ports:
        - name: grpc
          containerPort: 50050
        - name: http
          containerPort: 50051
        - name: kubernetes
          containerPort: 50052
        - name: log
          containerPort: 50055

---

apiVersion: v1
kind: Service

metadata:
  name: tko-api
  namespace: tko
  labels:
    app.kubernetes.io/name: tko-api
    app.kubernetes.io/part-of: tko

spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: tko-api
    app.kubernetes.io/part-of: tko
  ports:
  - name: grpc
    port: 50050
    nodePort: 30050
    targetPort: grpc
  - name: http
    port: 50051
    nodePort: 30051
    targetPort: http
  - name: kubernetes
    port: 50052
    nodePort: 30052
    targetPort: kubernetes
