apiVersion: v1
kind: Pod

metadata:
  name: tko-runner
  namespace: tko
  labels:
    app.kubernetes.io/name: tko-runner
    app.kubernetes.io/part-of: tko

spec:
  serviceAccountName: tko
  containers:
  - name: tko-runner
    image: tko-runner
    imagePullPolicy: Always
