apiVersion: apps/v1
kind: Deployment

metadata:
  name: tko-runner
  namespace: tko
  labels:
    app.kubernetes.io/name: tko-runner
    app.kubernetes.io/part-of: tko

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tko-runner
      app.kubernetes.io/part-of: tko
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tko-runner
        app.kubernetes.io/part-of: tko
    spec:
      containers:
      - name: tko-runner
        image: tko-runner
        imagePullPolicy: Always
        ports:
        - name: grpc
          containerPort: 50050

---

apiVersion: v1
kind: Service

metadata:
  name: tko-runner
  namespace: tko
  labels:
    app.kubernetes.io/name: tko-runner
    app.kubernetes.io/part-of: tko

spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: tko-runner
    app.kubernetes.io/part-of: tko
  ports:
  - name: grpc
    port: 50050
    targetPort: grpc
