apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

metadata:
  name: edge

name: edge1
networking:
  apiServerAddress: 127.0.0.1
  apiServerPort: 31001
  podSubnet: 10.98.0.0/16
  serviceSubnet: 10.198.0.0/16
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 32001
