apiVersion: v1
kind: Namespace

metadata:
  name: _ # placeholder for kpt set-namespace

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: free5gc-upf
  # namespace is missing

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: free5gc-upf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: free5gc-upf
    spec:
      containers:
      - name: nginx
        image: nginx:latest
